---
- name: Grub Configuration
  lineinfile: 
    dest: /etc/default/grub 
    regexp: ^GRUB_CMDLINE_LINUX= 
    line: GRUB_CMDLINE_LINUX="console=tty0 console=ttyS1,115200n8 biosdevname=0 rd.auto rd.auto=1 net.ifnames=1 numa_balancing=disable intel_pstate=disable intel_iommu=on iommu=pt isolcpus=2-55 nohz_full=2-55 rcu_nocbs=2-55 hugepagesz=2M hugepages=8096"
  register: grub_update

- name: Update Grub
  command: update-grub2
  when: ansible_os_family == "Debian" and grub_update.changed

- name: Update Grub
  shell: grub2-mkconfig -o "$(readlink /etc/grub2.cfg)"
  when: ansible_os_family == "RedHat" and grub_update.changed

- name: Reboot nodes after grub update
  reboot:
  when: grub_update.changed
