---
- name: Grub Configuration
  lineinfile: 
    dest: /etc/default/grub 
    regexp: ^GRUB_CMDLINE_LINUX= 
    line: GRUB_CMDLINE_LINUX="console=tty0 console=ttyS1,115200n8 biosdevname=0 rd.auto rd.auto=1 net.ifnames=1 hugepagesz=2M hugepages=8096 isolcpu=2-27,30-55, rcu_nocbs=2-27,30-55 nohz_full=2-27,30-55 nmi_watchdog=0 audit=0 nosoftlockup processor.max_cstate=1 intel_idle.max_cstate=1 hpet=disable tsc=reliable mce=off numa_balancing=disable intel_pstate=disable intel_iommu=on iommu=pt"
  register: grub_update

- name: Update Grub
  command: update-grub2
  when: ansible_os_family == "Debian" and grub_update.changed

- name: Update Grub
  shell: grub2-mkconfig -o "$(readlink /etc/grub2.cfg)"
  when: ansible_os_family == "RedHat" and grub_update.changed

- name: Reboot nodes after grub update
  reboot:
  when: grub_update.changed
