---
- name: Install requied python modules
  pip:
    name: ['pexpect','eventlet==0.22']

- name: Clone Repo
  git:
    repo: 'https://gerrit.fd.io/r/vpp'
    dest: /srv/vpp
    version: "{{vpp_commit}}"
    update: no

- name: Set VPP DPDK mlx5 PMD use
  lineinfile:
    dest: /srv/vpp/build-data/platforms/vpp.mk
    regexp: '^.*vpp_uses_dpdk_mlx5_pmd.*'
    line: 'vpp_uses_dpdk_mlx5_pmd = yes'

- name: Build Install Deb
  expect: 
    chdir: /srv/vpp
    command: make install-dep
    echo: yes
    responses:
      "Do you want to continue.*": "Y"
    timeout: 300

- name: get NASM code from launchpad
  get_url:
    url: https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/nasm/2.13.03-2/nasm_2.13.03.orig.tar.xz
    dest: /srv/vpp/dpdk/nasm_2.13.03.orig.tar.xz

- name: Build dpdk
  command: make dpdk-install-dev DPDK_MLX5_PMD=y DPDK_DOWNLOAD_DIR=/srv/vpp/dpdk NASM_VER=2.13.03 NASM_TARBALL=nasm_2.13.03.orig.tar.xz
  args:
    chdir: /srv/vpp

- name: Build release
  command: make build-release
  args:
    chdir: /srv/vpp

- name: Build pkg
  command: make pkg-deb vpp_uses_dpdk_mlx5_pmd=yes
  args:
    chdir: /srv/vpp
  when: ansible_os_family == 'Debian'

- name: find vpp debs to install
  find:
    paths: /srv/vpp
    recurse: yes
    patterns: "vpp_18*deb"
  register: vpp

- name: find vpp-lib debs to install
  find:
    paths: /srv/vpp
    recurse: yes
    patterns: "vpp-lib_18*.deb"
  register: vpp_lib

- name: find vpp-plugins debs to install
  find:
    paths: /srv/vpp
    recurse: yes
    patterns: "vpp-plugins_18*.deb"
  register: vpp_plugin

- name: find vpp-api-python debs to install
  find:
    paths: /srv/vpp
    recurse: yes
    patterns: "vpp-api-python_18*.deb"
  register: vpp_api_python

- name: Install vpp library packages
  command: dpkg -i {{item.path}}
  with_items: "{{vpp_lib['files']}}"

- name: Install vpp packages
  command: apt install {{item.path}}
  with_items: "{{vpp['files']}}"

- name: Install vpp plugins packages
  command: apt install {{item.path}}
  with_items: "{{vpp_plugin['files']}}"

- name: Install vpp api python packages
  command: apt install {{item.path}}
  with_items: "{{vpp_api_python['files']}}"

- name: Update vpp startup.conf for hugepage support
  template:
    src: startup.conf
    dest: /etc/vpp/startup.conf


- name: restart vpp service
  service:
    name: vpp
    state: restarted
