# Get chef and chef OpenStack cookbooks
- name: get chef package
  yum:
    name: https://packages.chef.io/files/stable/chefdk/3.4.38/el/7/chefdk-3.4.38-1.el7.x86_64.rpm
  when: ansible_os_family == 'RedHat'
- name: get chef package
  apt:
    deb: https://packages.chef.io/files/stable/chefdk/3.2.30/ubuntu/18.04/chefdk_3.2.30-1_amd64.deb
  when: ansible_os_family == 'Debian'
- name: get openstack-chef code 
  git: 
    repo: https://git.openstack.org/openstack/openstack-chef
    version: stable/queens
    dest: /root/openstack-chef
    update: false
  ignore_errors: True
    
- name: run the berks command in the openstack-chef repo
  command: berks install
  args:
    chdir: /root/openstack-chef
- name: move berks downloaded code to openstack-chef directory
  shell: tar cf - cookbooks/ | (cd /root/openstack-chef; tar xf -)
  args:
    chdir: /root/.berkshelf/
- name: Install chef client via the omnibus installer
  shell: curl -L https://omnitruck.chef.io/install.sh | bash

- name: Make /etc/chef directory
  file:
    state: directory
    dest: /etc/chef
    mode: 0664

- name: Move chef openstack secret to /etc/chef
  copy:
    src: /root/openstack-chef/.chef/encrypted_data_bag_secret
    dest: /etc/chef/openstack_data_bag_secret
    remote_src: True

# Update cookbooks, roles, and environments
- name: find the controller host address
  set_fact:
    host_0_address: "{{hostvars[groups['all'][0]].ansible_bond0.ipv4.address}}"

- name: Locally upload the chef recieps
  command: knife cookbook upload -a -z --include-dependencies --cookbook-path cookbooks/
  args:
    chdir: /root/openstack-chef/

- name: install updated environment file
  template:
    src: multinode.json
    dest: /root/openstack-chef/environments/multinode.json

- name: create openstack neutron config directory
  file:
    state: directory
    dest: /etc/neutron
    mode: 0755

- name: create an empty neutron plugin.ini file
  file:
    state: touch
    dest: /etc/neutron/plugin.ini
    mode: 0755

- name: Update the multinode-controller role
  template:
    src: multinode-controller.json
    dest: /root/openstack-chef/roles/multinode-controller.json

- name: Update the multinode-compute role
  template:
    src: multinode-compute.json
    dest: /root/openstack-chef/roles/multinode-compute.json

- name: Launch Chef based OpenStack installer on First (controller) node
  command: chef-client -z -E multinode -r 'role[multinode-controller]'
  args:
    chdir: /root/openstack-chef
  when: host_0_address == inventory_hostname
 
- name: Launch Chef based OpenStack installer on Other (compute) nodes
  command: chef-client -z -E multinode -r 'role[multinode-compute]'
  args:
    chdir: /root/openstack-chef
  when: not host_0_address == inventory_hostname
 
