---
- name: tasks file for Mellanox drivers
  hosts: localhost
  tasks:

    - name: Get tarball
      get_url:
        url: http://content.mellanox.com/ofed/MLNX_OFED-4.1-1.0.2.0/MLNX_OFED_LINUX-4.1-1.0.2.0-ubuntu16.04-x86_64.tgz
        dest: /tmp/MLNX_OFED_LINUX-4.1-1.0.2.0-ubuntu16.04-x86_64.tgz

    - name: Expand the tarball
      unarchive:
        src: /tmp/MLNX_OFED_LINUX-4.1-1.0.2.0-ubuntu16.04-x86_64.tgz
        dest: /tmp
        remote_src: true

    - name: Install the tarball
      command: ./mlnxofedinstall --all --force
      args: 
        chdir: /tmp/MLNX_OFED_LINUX-4.1-1.0.2.0-ubuntu16.04-x86_64

    - name: Restart openibd
      service: 
        name: openibd
        state: restarted

    
