- name: get VPP install script for RedHat
  get_url:
    url: https://packagecloud.io/install/repositories/fdio/release/script.rpm.sh
    dest: /root/vpp.sh
    mode: 0755
  when: ansible_os_family == "RedHat"
  register: vpp_sh_rh

- name: get VPP install script for Ubuntu
  get_url:
    url: https://packagecloud.io/install/repositories/fdio/release/script.deb.sh
    dest: /root/vpp.sh
    mode: 0755
  when: ansible_os_family == "Debian"
  register: vpp_sh_deb

- name: run VPP install script
  command: /root/vpp.sh
  when: vpp_sh_rh.changed or vpp_sh_deb.changed

- name: install dpdk on RedHat
  yum:
    name: ['libibverbs','dpdk']
  when: ansible_os_family == "RedHat"

- name: install dpdk on Debian
  yum:
    name: ['libibverbs-dev','dpdk']
  when: ansible_os_family == "Debian"

- name: install vpp service(s) RedHat
  yum:
    name: ["vpp","vpp-plugins","vpp-devel","vpp-api-python","vpp-api-lua","vpp-api-java"]
  when: ansible_os_family == "RedHat"

- name: install vpp service(s) Ubuntu
  apt:
    name: ["vpp","vpp-plugins","vpp-dev","vpp-dbg","vpp-api-python","vpp-api-lua","vpp-api-java"]
  when: ansible_os_family == "Debian"

- name: restart vpp service
  service:
    name: vpp
    state: restarted

- name: create ml2 config dir
  file:
    dest: /etc/neutron/plugins/ml2
    state: directory

- name: update ml2 config for vpp
  template:
    src: ml2_conf.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini

