---
- name: find the controller host address
  set_fact:
    host_0_address: "{{hostvars[groups['all'][0]].ansible_bond0.ipv4.address}}"


- name: update plugins config for vpp
  template:
    src: ml2_conf.j2
    dest: /etc/neutron/plugin.ini
    mode: 0644
  when: ansible_os_family == 'RedHat'

- name: update plugins config for vpp
  template:
    src: ml2_conf.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: install bridge utilities package - RedHat
  yum:
    name: bridge-utils
  when: ansible_os_family == 'RedHat'

- name: install bridge utilities package - Debian
  apt:
    name: bridge-utils
  when: ansible_os_family == 'Debian'

- name: enable python pip - RedHat
  yum:
    name: ['python-devel','python-pip']
  when: ansible_os_family == "RedHat"

- name: enable python pip - Debian
  yum:
    name: ['python-dev','python-pip']
  when: ansible_os_family == "Debian"

- name: get vpp plugin code
  git:
    repo: https://github.com/openstack/networking-vpp
    dest: /root/networking-vpp
    version: "{{vpp_branch}}"
    update: no

- name: install openstack networking-vpp plugin
  pip:
    name: /root/networking-vpp

- name: migrate neutron vpp database
  command: neutron-db-manage --subproject networking-vpp --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugin.ini upgrade head
  when: ansible_os_family == 'RedHat'

- name: migrate neutron vpp database
  command: neutron-db-manage --subproject networking-vpp --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  when: ansible_os_family == 'Debian'

#- name: bring ex-slave interface down
#  command: ifdown {{vlan_interface}}
#  ignore_errors: true

- name: add vpp-agent script
  template:
    src: vpp-agent
    dest: /usr/local/bin/vpp-agent
    mode: 0755

- name: add vpp-agent systemd service - RedHat
  template:
    src: vpp-agent-redhat.service
    dest: /usr/lib/systemd/system/vpp-agent.service
    mode: 0644
  when: ansible_os_family == 'RedHat'

- name: add vpp-agent systemd service - Debian
  template:
    src: vpp-agent-debian.service
    dest: /lib/systemd/system/vpp-agent.service
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: add vpp-agent multi-user.wants link - RedHat
  file:
    state: link
    src: /usr/lib/systemd/system/vpp-agent.service
    dest: /etc/systemd/system/multi-user.target.wants/vpp-agent.service
  when: ansible_os_family == 'RedHat' and inventory_hostname == host_0_address
  notify:
  - Restart neutron-server
  - Restart vpp-agent

- name: add vpp-agent multi-user.wants link - Debian
  file:
    state: link
    src: /lib/systemd/system/vpp-agent.service
    dest: /etc/systemd/system/multi-user.target.wants/vpp-agent.service
  when: ansible_os_family == 'Debian'
  notify:
  - Restart neutron-server
  - Restart vpp-agent

- name: add hugepage support for nova
  ini_file:
    path: /etc/nova/nova.conf
    section: DEFAULT
    option: reserved_huge_pages
    value: node:0,size:2048,count:64
  notify:
  - Restart openstack-nova-compute

- name: ensure Neutron plugin is defined - Debian
  lineinfile:
    path: /etc/default/neutron-server
    regexp: 'NEUTRON_PLUGIN_CONFIG=.*'
    line: 'NEUTRON_PLUGIN_CONFIG=/etc/neutron/plugins/ml2/ml2_conf.ini'
  when: ansible_os_family == 'Debian' and inventory_hostname == host_0_address
  notify:
  - Restart neutron-server

- name: Daemon Reload
  systemd:
    daemon_reload: yes
  notify:
  - Restart neutron-server
  - Restart vpp-agent
