---
# curl -L https://packagecloud.io/fdio/release/gpgkey |sudo apt-key add -
- name: Add packagecloud gpg key
  apt_key:
    url: https://packagecloud.io/fdio/release/gpgkey
    state: present

- name: setup vpp repo for RedHat
  template:
    src: fdio.repo
    dest: /etc/yum.repos.d/fdio.repo
  when: ansible_os_family == "RedHat"
  register: vpp_sh_rh

#- name: get VPP install script for RedHat
#  get_url:
#    url: https://packagecloud.io/install/repositories/fdio/release/script.rpm.sh
#    dest: /root/vpp.sh
#    mode: 0755
#  when: ansible_os_family == "RedHat"
#  register: vpp_sh_rh


- name: setup vpp repo for Ubuntu
  template:
    src: 99fd.io.list
    dest: /etc/apt/sources.list.d/99fd.io.list
  when: ansible_os_family == "Debian"
  register: vpp_sh_deb

#- name: get VPP install script for Ubuntu
#  get_url:
#    url: https://packagecloud.io/install/repositories/fdio/release/script.deb.sh
#    dest: /root/vpp.sh
#    mode: 0755
#  when: ansible_os_family == "Debian"
#  register: vpp_sh_deb

#- name: run VPP install script
#  command: /root/vpp.sh
#  when: vpp_sh_rh.changed or vpp_sh_deb.changed
#
- name: install dpdk on RedHat
  yum:
    name: ['libibverbs','dpdk']
  when: ansible_os_family == "RedHat"

- name: install dpdk on Debian
  yum:
    update_cache: yes
    name: ['libibverbs-dev','dpdk']
  when: ansible_os_family == "Debian"

- name: install vpp service(s) RedHat
  yum:
    name: ["vpp","vpp-plugins","vpp-devel"]
  when: ansible_os_family == "RedHat"

- name: install vpp service(s) Ubuntu
  apt:
    update_cache: yes
    name: ["vpp","vpp-plugins","vpp-dev","vpp-dbg", "vpp-lib"]
  when: ansible_os_family == "Debian"

- name: install vpp api packages(s) RedHat
  yum:
    name: ["vpp-api-python","vpp-api-lua","vpp-api-java"]
  when: ansible_os_family == "RedHat"

# - name: install vpp api packages(s) Ubuntu
#   apt:
#     update_cache: yes
#     name: ["vpp-api-python","vpp-api-lua","vpp-api-java"]
#   when: ansible_os_family == "Debian"
