# Default values for vedge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: denverwilliams/cnfs
  tag: vedge_single
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

resources: 
  limits:
   cpu: "3"
   hugepages-2Mi: 200Mi
