---
- hosts: all
  pre_tasks:
  - setup:
  roles:
    - role: packet_l2
      delegate_to: localhost
      run_once: true
      connection: local
      vars:
        facility: "{{ lookup('env','PACKET_FACILITY') }}"
        deploy_env: osnrt
        server_list: "{{ lookup('env','SERVER_LIST') }}"
        project_name: "CNCF CNFs"
        vlans:
          vlan1:
            interface: "eth1"
          vlan2:
            interface: "eth1"
    - role: retr0h.etcd
      vars:
        etcd_interface: bond0
    - chef_openstack_install
    - role: vpp_install 
      vars: 
        vpp_branch: stable.1810 # fd.io repo
    - role: vpp_openstack
      vars:
        vpp_branch: '1810'
