---
- hosts: all
  pre_tasks:
  - name: Apt update
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Install EPEL Package
    yum:
      name: epel-release
    when: ansible_os_family == "RedHat"
  - name: Yum update
    yum:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_os_family == "RedHat"

  - name: Install Vlan Package
    apt:
      name: vlan
    when: ansible_os_family == "Debian"
  - name: Install Vlan Package
    yum:
      name: vconfig
    when: ansible_os_family == "RedHat"

  - name: Server list
    debug: var=server_list


  tasks:
  - name: Get Bond0 Slave1 interface
    set_fact:
      vlan_interface: "{{ansible_bond0.slaves[1]}}"
    when: ansible_bond0.slaves[1] is defined

  - name: Get Bond0 Slave1 PCIid
    set_fact:
      vlan_pciid: "{{hostvars[inventory_hostname]['ansible_' + vlan_interface]['pciid']}}"
    when: ansible_bond0.slaves[1] is defined

  - name: updated vlan data
    debug: var=vlans

  - name: Add host and VPP interface to inventory
    delegate_to: localhost
    shell: echo "{{inventory_hostname}} vlan_interface={{vlan_interface}} vlan_pciid={{vlan_pciid}}" >> /ansible/inventory
    when: ansible_bond0.slaves[1] is defined

  roles:
    - role: ntp
    - role: packet_vlan_enable
      when: ansible_bond0.slaves[1] is defined
    - role: grub_openstack
