---
- hosts: all
  vars:
    vpp_network: false
    create_vlans: false
  pre_tasks:
  - setup:
  roles:
    - role: packet_l2
      delegate_to: localhost
      run_once: true
      connection: local
      vars:
        facility: "{{ lookup('env','PACKET_FACILITY') }}"
        deploy_env: os
        server_list: "{{ lookup('env','SERVER_LIST') }}"
        project_name: "{{ lookup('env','PROJECT_NAME') }}"
        vlans:
          vlan1:
            interface: "eth1"
          vlan2:
            interface: "eth1"
      when: create_vlans
    - role: retr0h.etcd
      vars:
        etcd_interface: bond0
      when: vpp_network
    - chef_openstack_install
    - role: vpp_install 
      vars: 
        vpp_branch: stable.1810 # fd.io repo
      when: vpp_network
    - role: vpp_openstack
      vars:
        vpp_branch: '1810'
      when: vpp_network
    - role: openstack_scripts
