---
- hosts: all
  pre_tasks:
  - setup:
  roles:
    - role: retr0h.etcd
      vars:
        etcd_interface: bond0
    - chef_openstack_install
    - role: vpp_install 
      vars: 
        vpp_branch: stable.1810 # fd.io repo
    - vpp_openstack
