---
- hosts: all
  vars:
    vlan_interface: enp94s0f1
    vlan_pci_id: 0000:5e:00.1
    vpp_network: true
    create_vlans: true
  pre_tasks:
  - setup:
  roles:
    - role: packet_l2
      delegate_to: localhost
      run_once: true
      connection: local
      vars:
        facility: "{{ lookup('env','PACKET_FACILITY') }}"
        deploy_env: mlxtest 
        server_list: "{{ lookup('env','SERVER_LIST') }}"
        project_name: "{{ lookup('env','PROJECT_NAME') }}"
        vlans:
          vlan1:
            interface: "eth1"
          vlan2:
            interface: "eth1"
      when: create_vlans

    - role: retr0h.etcd
      vars:
        etcd_interface: bond0
      when: vpp_network

    - role: chef_openstack_install
    - role: openstack_ovs_provider
      when: not vpp_network
    - role: openstack_scripts
    - role: openstack_vnc_fix

    - role: vpp_src_install
      when: vpp_network
    - role: vpp_openstack
      when: vpp_network
