- name: intall ntp client on centos
  yum:
    name: ['ntp','git-core']
  when: ansible_os_family == "RedHat"


- name: install ntp client on debian
  apt:
    name: ['ntp','git']
  when: ansible_os_family == "Debian"

- name: sync ntp
  command: ntpq -np

- name: start ntp service on centos
  service:
    name: ntpd
    state: restarted
  when: ansible_os_family == "RedHat"

- name: start ntp service on debian
  service:
    name: ntp
    state: restarted
  when: ansible_os_family == "Debian"
