---
- name: Fetch nodes
  shell: > 
            ls /sys/devices/system/node/ | 
            grep node | 
            paste -s -d ','
  register: result

- name: Prepare Hugepages
  command: echo 4096 > /sys/devices/system/node/{{ item }}/hugepages/hugepages-2048kB/nr_hugepages
  with_items: "{{ result.stdout.split(',') }}"

- name: Mount Hugepages
  mount: 
    path: /dev/hugepages
    src: none
    fstype: hugetlbfs
    opts: pagesize=2M
    state: present

- name: Get Kernal Version
  setup: 
    filter: "{{ ansible_kernel }}"

- name: Docker start opnfv/nfvbench
  docker_container:
    name: nfvbench
    image: opnfv/nfvbench:1.5.2
    state: started
    network_mode: host
    privileged: true
    volumes: 
      - "{{ playbook_dir }}:/tmp/nfvbench"
      - /dev:/dev
      - /lib/modules/{{ ansible_kernel }}:/lib/modules/{{ ansible_kernel }}
      - /usr/src:/usr/src
      - /usr/bin/ofed_info:/usr/bin/ofed_info
      - /etc/libibverbs.d:/etc/libibverbs.d
      - /usr/lib:/tmp/lib
      - /dev/mst:/dev/mst
      - /usr/lib:/usr/lib
      - /lib:/lib

- name: Update the number of hugepages available for TRex
  command: docker exec -i nfvbench sed -i -e "s/512 /2048 /" -e "s/512\"/2048\"/" /opt/trex/v2.32/trex-cfg

- name: Change the mbuf factor to further reduce the memory usage
  command: docker exec -i nfvbench sed -i -e "s/--cfg {} \&>/--cfg {} --mbuf-factor 0.2 \&>/g" /nfvbench/nfvbench/traffic_server.py

- name: Add alias for running nfvbench
  lineinfile: 
    path: /root/.bashrc
    line: 'alias nfvbench="sudo docker exec -it nfvbench nfvbench -c /tmp/nfvbench/nfvbench_config.cfg"'
