---
- name: Fetch nodes
  shell: > 
            ls /sys/devices/system/node/ | 
            grep node | 
            paste -s -d ','
  register: result

- name: Prepare Hugepages
  command: echo 4096 > /sys/devices/system/node/{{ item }}/hugepages/hugepages-2048kB/nr_hugepages
  with_items: "{{ result.stdout.split(',') }}"

- name: Mount Hugepages
  mount: 
    path: /dev/hugepages
    src: none
    fstype: hugetlbfs
    opts: pagesize=2M
    state: present
