heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: xenial
      flavor: hp.small
      config_drive: True
      user_data: |
        #!/bin/bash
        passwd ubuntu <<EOF
        ubuntu
        ubuntu
        EOF
      networks:
        network: vlan1056
