---
- name: Apt update
  apt: 
    update_cache: yes

- name: Install git
  apt:
    name: git

- name: Clone Repo
  git:
    repo: 'https://gerrit.fd.io/r/vpp'
    dest: /srv/vpp
    version: origin/stable/1807

- name: Set VPP Users
  command: sed -i '/vpp_uses_dpdk_mlx5_pmd/s/^# //g' build-data/platforms/vpp.mk 
  args:
    chdir: /srv/vpp

- name: Build Install Deb
  expect: 
    chdir: /srv/vpp
    command: make install-dep
    echo: yes
    responses:
      "Do you want to continue.*": "Y"
    timeout: 300

- name: Build dpdk
  command: make dpdk-install-dev DPDK_MLX5_PMD=y
  args:
    chdir: /srv/vpp

- name: Build release
  command: make build-release
  args:
    chdir: /srv/vpp

- name: Build pkg
  command: make pkg-deb vpp_uses_dpdk_mlx5_pmd=yes
  args:
    chdir: /srv/vpp

- name: Install vpp-lib
  command: dpkg -i build-root/vpp-lib_18.07.1-11~g31aa6f26-dirty_amd64.deb
  args: 
    chdir: /srv/vpp

- name: Install vpp_18
  command: dpkg -i build-root/vpp_18.07.1-11~g31aa6f26-dirty_amd64.deb
  args:
    chdir: /srv/vpp

- name: Intall vpp plugins
  command: dpkg -i build-root/vpp-plugins_18.07.1-11~g31aa6f26-dirty_amd64.deb
  args:
    chdir: /srv/vpp

- name: Create vpp directory
  file: path=/etc/vpp/sockets state=directory

- name: Write vpp baseline startup config file
  template: src=vEdge_baseline_startup.conf.j2 dest=/etc/vpp/startup.conf
  when: baseline

- name: Write vpp startup config file
  template: src=vEdge_startup.conf.j2 dest=/etc/vpp/startup.conf
  when: not baseline

- name: Update CNF VPP configuration
  template: src=vEdge_cnf.conf.j2 dest=/etc/vpp/setup.gate
  when: cnf

- name: Update VNF VPP configuration
  template:  src=vEdge_vnf.conf.j2 dest=/etc/vpp/setup.gate
  when: vnf

- name: Restart vpp
  service: 
    name: vpp
    state: restarted

- name: Write hugepages sys.conf
  template: src=80-vpp.conf.j2 dest=/etc/sysctl.d/80-vpp.conf

- name: Refresh sysctl
  command: sysctl -p
