apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vedge.fullname" . }}
  labels:
    app: {{ template "vedge.name" . }}
    chart: {{ include "vedge.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  setup.gate: |-
    bin memif_socket_filename_add_del add id 1 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}{{ .Values.sock1 }}.sock
    bin memif_socket_filename_add_del add id 2 filename {{ .Values.volumeMounts.vpp_sockets.mountPath }}{{ .Values.sock2 }}.sock
    create interface memif id {{ .Values.memid1 }} socket-id 1 hw-addr {{ .Values.mac1 }} {{ .Values.owner1 }} rx-queues {{ .Values.queues }} tx-queues {{ .Values.queues }}
    create interface memif id {{ .Values.memid2 }} socket-id 2 hw-addr {{ .Values.mac2 }} {{ .Values.owner2 }} rx-queues {{ .Values.queues }} tx-queues {{ .Values.queues }}
    set int ip addr memif1/{{ .Values.memid1 }} {{ .Values.subnet1 }}
    set int ip addr memif2/{{ .Values.memid2 }} {{ .Values.subnet2 }}
    set int state memif1/{{ .Values.memid1 }} up
    set int state memif2/{{ .Values.memid2 }} up
    set ip arp static memif1/{{ .Values.memid1 }} {{ .Values.remip1 }} {{ .Values.remmac1 }}
    set ip arp static memif2/{{ .Values.memid2 }} {{ .Values.remip2 }} {{ .Values.remmac2 }}
    ip route add 172.16.64.0/18 via {{ .Values.remip1 }}
    ip route add 172.16.192.0/18 via {{ .Values.remip2 }}
  startup.conf: |-
    unix {
      nodaemon
      interactive
      log /var/log/vpp/vpp.log
      full-coredump
      cli-listen /run/vpp/cli.sock
      gid vpp
      startup-config /etc/vpp/setup.gate
    }

    api-trace {
      on
    }

    api-segment {
      gid vpp
    }

    cpu {
      main-core {{ .Values.mainCore }}
      corelist-workers {{ .Values.corelistWorkers }}
    }
 
    dpdk {
      no-pci
      uio-driver igb_uio
      no-multi-seg
      socket-mem {{ .Values.socketMem }}
      no-tx-checksum-offload
    }

    plugins {
      plugin default { disable }
      plugin dpdk_plugin.so { enable }
      plugin memif_plugin.so { enable }
    }
