# Default values for vedge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: soelvkaer/vppcontainer
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: "5"
    hugepages-2Mi: 200Mi

volumeMounts:
  vpp_sockets:
    mountPath: /etc/vpp/sockets/

physintf1: "TenGigabitEthernet1a/0/1"
physpci1: 0000:1a:00.1

physintf2: "TenGigabitEthernet1a/0/2"
physpci2: 0000:1a:00.2

mainCore: 0
corelistWorkers: 2,4
#corelistWorkers: 2,4,30,32

rxqueues: 2

