- name: get chef package
  yum:
    name: https://packages.chef.io/files/stable/chefdk/3.4.38/el/7/chefdk-3.4.38-1.el7.x86_64.rpm
  when: ansible_os_family == 'RedHat'
- name: get openstack-chef code 
  git: 
    repo: https://git.openstack.org/openstack/openstack-chef
    dest: /root/openstack-chef
  ignore_errors: True
    
- name: run the berks command in the openstack-chef repo
  command: berks install
  args:
    chdir: /root/openstack-chef
- name: move berks downloaded code to openstack-chef directory
  shell: tar cf - cookbooks/ | (cd /root/openstack-chef; tar xf -)
  args:
    chdir: /root/.berkshelf/

