- hosts: localhost
  vars: 
    vlan_name: testvlan1
    project_name: CNCF CNFs
    facility: ewr1
    server_list:
      - quadtestb-07
      - quadtestb-08
    vlans:
      testvlan1:
        vid:
        interface: eth1
      testvlan2:
        vid:
        interface: eth2
      testvlan3:
        vid:
        interface: eth3

  tasks:
  - name: Show vlan data before create
    debug: var=vlans
 
  - name: Create My Vlans
    command: ruby /packet_api/l2_packet_networking.rb --create-vlan={{ item.key }} --project-name="{{ project_name }}" --packet-url='api.packet.net' --facility="{{ facility }}"
    with_dict: "{{ vlans }}"
    register: vlandata
  
  - name: store vlan id
    set_fact:
      vlans: "{{ vlans|combine({item.item.key: {'vid': item.stdout }}, recursive=True) }}"
    with_items: "{{ vlandata.results }}"

  - name: updated vlan data
    debug: var=vlans

  - name: Remove interface from bond0, for all specifed nodes
    command: ruby /packet_api/l2_packet_networking.rb --server={{ item[0] }} --disbond-interface={{ vlans[item[1]].interface }} --project-name="{{ project_name }}"  --packet-url='api.packet.net'
    with_nested:
      - "{{ server_list }}"
      - "{{ vlans }}"

  - name: Assign vlan to interface
    command: ruby /packet_api/l2_packet_networking.rb --server={{ item[0] }} --assign-vlan-id={{ vlans[item[1]].vid }} --assign-vlan-port={{ vlans[item[1]].interface }} --project-name="{{ project_name }}" --packet-url='api.packet.net'
    with_nested:
      - "{{ server_list }}"
      - "{{ vlans }}"

 ### Tear things down and put it back to the default setup

  - name: Unassign vlan to interface
    command: ruby /packet_api/l2_packet_networking.rb --server={{ item[0] }} --unassign-vlan-id={{ vlans[item[1]].vid }} --unassign-vlan-port={{ vlans[item[1]].interface }} --project-name="{{ project_name }}" --packet-url='api.packet.net'
    with_nested:
      - "{{ server_list }}"
      - "{{ vlans }}"

  - name: Add interface to bond0, for all specifed nodes
    command: ruby /packet_api/l2_packet_networking.rb --server={{ item[0] }} --bond-interface={{ vlans[item[1]].interface }} --project-name="{{ project_name }}"  --packet-url='api.packet.net'
    with_nested:
      - "{{ server_list }}"
      - "{{ vlans }}"

  - name: Delete my vlans
    command: ruby /packet_api/l2_packet_networking.rb --delete-vlan={{ item.key }} --project-name="{{ project_name }}" --packet-url='api.packet.net' --facility="{{ facility }}"
    with_dict: "{{ vlans }}"
    register: vlandata
