project_name: CNCF CNFs
facility: ewr1
deploy_env: cnftest
delete_vlan: false
unassign_interface: false
add_interface_to_bond: false
vlans:
  testvlan1:
    vid:
    interface: eth1
  testvlan2:
    vid:
    interface: eth1
